call plug#begin()

" Plugins
Plug 'ycm-core/YouCompleteMe', { 'do': './install --clang-completer --ts-completer' }  " Code completion
Plug 'tpope/vim-surround'                                                              " Surround
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }                      " Fuzzy file search
Plug 'junegunn/fzf.vim'                                                                " Fuzzy file search
Plug 'tpope/vim-fugitive'                                                              " Git wrapper
Plug 'mileszs/ack.vim'                                                                 " Ack search tool
Plug 'airblade/vim-gitgutter'                                                          " Gitgutter
Plug 'vim-airline/vim-airline'                                                         " Airline statusline
Plug 'leafgarland/typescript-vim'                                                      " TypeScript highlighting
Plug 'morhetz/gruvbox'                                                                 " Gruvbox theme

call plug#end()

colorscheme gruvbox                 " Enable theme
filetype plugin indent on           " Enabling filetype support provides filetype-specific indenting,
syntax on                           " Syntax highlighting, omni-completion and other useful settings.

" fzf setup
function! s:find_git_root()
  return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
endfunction
command! ProjectFiles execute 'Files' s:find_git_root()
nnoremap <c-P> :ProjectFiles<CR>
let $FZF_DEFAULT_COMMAND = 'ag -g ""'

" Keybindings
" Stop space from moving cursor
nnoremap <SPACE> <Nop>
let mapleader = "\<Space>" " Assign space as leader
nnoremap <leader><leader> <C-^>
" Ctrl + direction to move between splits
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
" Use ; for entering commands
nnoremap ; :
" Make 'Y' yank from cursor to end of line
nnoremap Y y$
" Clear search with ,/
nnoremap <silent> ,/ :nohlsearch<CR>

if executable('ag')
  set grepprg=ag\ --nogroup\ --nocolor " Use Ag over Grep
  let g:ackprg = 'ag --nogroup --nocolor --column' " Use ag in place of ack
endif

runtime macros/matchit.vim " Hit `%` on `if` to jump to `else`.

if has ('autocmd') " Remain compatible with earlier versions
  " Use actual tab chars in Makefiles.
  autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
  augroup vimrc     " Source vim configuration upon save
    autocmd! BufWritePost $MYVIMRC source % | echom "Reloaded " . $MYVIMRC | redraw
    autocmd! BufWritePost $MYGVIMRC if has('gui_running') | so % | echom "Reloaded " . $MYGVIMRC | endif | redraw
  augroup END
endif " has autocmd

" various settings
set autoindent                                    " Minimal automatic indenting for any filetype.
set smartindent                                   " Better autoindent e.g. extra indent after parens
set backspace=indent,eol,start                    " Proper backspace behavior.
set hidden                                        " Possibility to have more than one unsaved buffers.
set incsearch                                     " Incremental search, hit `<CR>` to stop.
set ruler                                         " Shows the current line number at the bottom-right of the screen.
set wildmenu                                      " Great command-line completion, use `<Tab>` to move around.
set ignorecase                                    " Case insensitive search default
set smartcase                                     " Case sensitive search if capital in search string
set confirm                                       " Ask to save instead of failing command requiring save
set hlsearch                                      " Highlight search matches
set showmatch                                     " Highlight matching parens etc
set laststatus=2                                  " Always show the statusline
set list                                          " Display trailing whitespace
set listchars=tab:>-,trail:~,extends:>,precedes:< " Display trailing whitespace as ~
set showcmd                                       " Show the command as it is being typed at bottom of screen
set autoread                                      " Automatically reload file on change
set bg=dark                                       " Enable dark mode
set updatetime=100                                " Set refresh to 100ms
set noerrorbells                                  " No beeping
set undofile                                      " Maintain undo history between sessions
set undodir=~/.vim/undodir//                      " Store undofiles in single directory
set noswapfile                                    " Disable swapfiles
set tabstop=2                                     " The width of a TAB is set to 2.
set shiftwidth=2                                  " Indents will have a width of 2
set softtabstop=2                                 " Sets the number of columns for a TAB
set expandtab                                     " Expand TABs to spaces

" Hybrid line numbers, relative in visual and absolute other times
set number relativenumber
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

